



---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-credentials
  namespace: temporal
type: Opaque
stringData:
  rootUser: root
  rootHost: "%"
  rootPassword: "Aa123456"
---
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysql
  namespace: temporal
spec:
  secretName: mysql-root-credentials
  instances: 1
  router:
    instances: 1
  tlsUseSelfSigned: true
  datadirVolumeClaimTemplate:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
  initDB:
    clone: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
  namespace: temporal
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS temporal;
    CREATE DATABASE IF NOT EXISTS temporal_visibility;
    CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY 'Aa123456';
    GRANT ALL PRIVILEGES ON temporal.* TO 'admin'@'%';
    GRANT ALL PRIVILEGES ON temporal_visibility.* TO 'admin'@'%';
    FLUSH PRIVILEGES;
