##############################################################################
# Note!
# Secrets must stay empty.
# the context of the secrets is generated be terraform (secrets.tf)
# https://github.com/leomerl/full-devops-k8s-iac-solution/blob/argo/03-cluster-bootstrap/secrets.tf
#
# and replicated by reflector:
# https://github.com/leomerl/full-devops-k8s-iac-solution/tree/argo/03-cluster-bootstrap/applicationsets/reflector-applicationse.yaml
##############################################################################


apiVersion: v1
kind: Secret
metadata:
 name: docker-cred
 annotations:
   reflector.v1.k8s.emberstack.com/reflects: "devops-utils/docker-cred"
data:

---

apiVersion: v1
kind: Secret
metadata:
 name: github-token
 annotations:
   reflector.v1.k8s.emberstack.com/reflects: "devops-utils/github-token"
data:

