controller:
  admin:
    # -- Admin username created as a secret if `controller.admin.createSecret` is true
    username: "admin"
    # -- Admin password created as a secret if `controller.admin.createSecret` is true
    # @default -- <random password>
    password: "Aa123456"
    jenkinsAdminEmail: "eyal@levys.co.il"

  serviceType: NodePort
  nodePort: 32001

  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - pipeline-stage-view:latest
    - configuration-as-code:latest
    - job-dsl:latest

  sidecars:
    configAutoReload:
      enabled: true
  JCasC:
    configUrls: []
    configScripts: {}

  extraVolumes:
    - name: casc-jobs
      configMap:
        name: jenkins-casc-jobs

  extraVolumeMounts:
    - name: casc-jobs
      mountPath: /var/jenkins_home/casc_config/jobs.yaml
      subPath: jobs.yaml

