controller:
  admin:
    # -- Admin username created as a secret if `controller.admin.createSecret` is true
    username: "admin"
    # -- Admin password created as a secret if `controller.admin.createSecret` is true
    # @default -- <random password>
    password: "Aa123456"
    jenkinsAdminEmail: "eyal@levys.co.il"

  serviceType: NodePort
  nodePort: 32001

  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - pipeline-stage-view:latest
    - configuration-as-code:latest
    - job-dsl:latest

  JCasC:
    configScripts:
      credentials: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - string:
                      scope: GLOBAL
                      id: "github-token"
                      secret: "${GITHUB_TOKEN}"
                      description: "GitHub PAT"
      jobs: |
        jobs:
          - script: >
              pipelineJob('hello-newapp') {
                triggers {
                  scm('* * * * *')
                }
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote {
                          url('https://github.com/elevy99927/hello-newapp.git')
                        }
                        branches('*/argo-solution')
                      }
                    }
                    scriptPath('Jenkinsfile')
                  }
                }
              }
