apiVersion: v1
kind: ServiceAccount
metadata:
  name: application-d
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: application-d-config
data:
  APP_NAME: application-d
  TEAM: team-b
  ENV: prd
---
apiVersion: v1
kind: Secret
metadata:
  name: application-d-secret
type: Opaque
stringData:
  API_KEY: changeme
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-d
spec:
  selector:
    matchLabels:
      app: application-d
  replicas: 1
  template:
    metadata:
      labels:
        app: application-d
    spec:
      serviceAccountName: application-d
      containers:
      - name: color
        image: elevy99927/color:blue
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: application-d-config
        - secretRef:
            name: application-d-secret
---
apiVersion: v1
kind: Service
metadata:
  name: application-d
spec:
  selector:
    app: application-d
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: application-d
spec:
  ingressClassName: nginx
  rules:
  - host: application-d.team-b.prd.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: application-d
            port:
              number: 80
