apiVersion: v1
kind: ServiceAccount
metadata:
  name: application-b
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: application-b-config
data:
  APP_NAME: application-b
  TEAM: team-a
  CLUSTER: dev
  NAMESPACE: frontend-ns
---
apiVersion: v1
kind: Secret
metadata:
  name: application-b-secret
type: Opaque
stringData:
  API_KEY: changeme
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-b
spec:
  selector:
    matchLabels:
      app: application-b
  replicas: 1
  template:
    metadata:
      labels:
        app: application-b
    spec:
      serviceAccountName: application-b
      containers:
      - name: color
        image: elevy99927/color:yellow
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: application-b-config
        - secretRef:
            name: application-b-secret
---
apiVersion: v1
kind: Service
metadata:
  name: application-b
spec:
  selector:
    app: application-b
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: application-b
spec:
  ingressClassName: nginx
  rules:
  - host: application-b.frontend-ns.team-a.dev.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: application-b
            port:
              number: 80
