apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: systems-dynamic
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/elevy99927/argo-demo-repo.git
        revision: example-2-dynamic-generator
        files:
          - path: systems/*/qa/*.yaml        # systems/<team>/<env>/<app>.yaml
  template:
    metadata:
      # .path.segments = [systems, team-a, qa]   .path.filename = application-a.yaml
      name: '{{index .path.segments 1}}-{{.path.basename}}-{{.path.filename | trimSuffix ".yaml"}}'   # team-a-qa-application-a
    spec:
      project: default
      source:
        repoURL: https://github.com/elevy99927/argo-demo-repo.git
        targetRevision: example-2-dynamic-generator
        path: '{{.path.path}}'            # systems/team-a/qa
        directory:
          include: '{{.path.filename}}'   # only this app's file, not the whole folder
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 1}}-{{.path.basename}}'   # team-a-qa
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
