apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: systems-dynamic
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/elevy99927/argo-demo-repo.git
        revision: example-2-dynamic-generator
        directories:
          - path: systems/*/qa/*/*        # systems/<team>/<env>/<ns>/<app>
  template:
    metadata:
      # .path.segments = [systems, team-a, qa, frontend-ns, application-a]
      name: '{{index .path.segments 1}}-{{index .path.segments 2}}-{{index .path.segments 3}}-{{.path.basename}}'   # team-a-qa-frontend-ns-application-a
    spec:
      project: default
      source:
        repoURL: https://github.com/elevy99927/argo-demo-repo.git
        targetRevision: example-2-dynamic-generator
        path: '{{.path.path}}'            # systems/team-a/qa/frontend-ns/application-a
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 3}}'   # frontend-ns
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
