apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app1
spec:
  selector:
    matchLabels:
      app: color
  replicas: 1
  template:
    metadata:
      labels:
        app: color
    spec:
      containers:
      - name: color
        image: elevy99927/color:blue
        ports:
        - containerPort: 80
